import type { Metadata } from "next";
import "./globals.css";
import { adelle, ceraProBold } from "./fonts";
import { Toaster } from "@/components/ui/toaster";
// import Header from "@/components/Header";
// import SideNavbar from "@/components/Sidebar";
import '../amplifyconfig'; // Adjust path if needed


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${adelle.variable} ${ceraProBold.className} font-semibold`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
